version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: 5mirnovvv/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    env_file: .env
    image: 5mirnovvv/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static
  gateway:
    image: 5mirnovvv/kittygram_gateway
    depends_on:
      - backend
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media/


